// Extracted verbatim from the Ruhi prototype. 28 slices, illustrative values.
// Replace with a licensed valuation feed before launch — see README "Data".

const D = [
["uslg","US Large Growth","US size & style",96,"31.4","44.1","12.1","0.5%","+16%","-2%","-34%","+21%","+19%","+18%","+17.5%","19","0.97","+$48B","VUG|Vanguard Growth|0.04;SCHG|Schwab US Large-Cap Growth|0.04;IWF|iShares Russell 1000 Growth|0.19","Six or seven companies carry the index, and they are priced for the AI capital cycle to convert into durable operating profit. At the 96th percentile of its own twenty-year range, the slice is discounting execution, not hoping for it.","Nothing here is broken — earnings have genuinely compounded. The issue is arithmetic: buying at this multiple has historically front-loaded a decade of return into the price you pay today.","Top-ten weight near 55% of the index — this is a concentrated bet, not diversification;AI capital spending that does not convert to returns on invested capital;Multiple compression if long real rates move higher;Crowding — the same names sit inside most US core funds you already own","Jan 2026"],
["uslb","US Large Blend","US size & style",91,"22.6","38.2","5.2","1.2%","+11%","-1%","-34%","+14%","+14%","+15%","+13.8%","16","1.00","+$120B","VOO|Vanguard S&P 500|0.03;SPLG|SPDR Portfolio S&P 500|0.02;ITOT|iShares Core S&P Total US|0.03","The default holding for most portfolios, and currently the 91st percentile of its own history. Growth's weight inside the blend index is doing most of the work.","Owning it is defensible; expecting the last decade's return from this entry point is not. Cap-weighting means you are buying more of what has already risen.","Growth concentration imported into a supposedly neutral holding;Margins at cycle highs — mean reversion would hit the E, not just the P/E;Passive flows reverse the same way they arrive","Feb 2026"],
["uslv","US Large Value","US size & style",68,"17.2","26.4","2.9","2.2%","+7%","-3%","-32%","+11%","+11%","+12%","+9.6%","14","0.88","+$9B","VTV|Vanguard Value|0.04;SCHV|Schwab US Large-Cap Value|0.04;IWD|iShares Russell 1000 Value|0.19","Cheaper than the blend on every multiple, but not cheap against its own history — value has re-rated alongside everything else. Financials and healthcare dominate the exposure.","The spread between value and growth multiples is wide; the absolute level of value is only middling. That combination argues for a tilt, not a wholesale move.","Financials are roughly a quarter of the index — this is a rate and credit bet;Value traps in structurally declining industries;Less earnings growth means the multiple has to do more of the work","Jan 2026"],
["usmg","US Mid Growth","US size & style",74,"24.8","30.1","5.4","0.7%","+12%","-8%","-41%","+9%","+8%","+11%","+10.9%","20","0.92","-$2B","VOT|Vanguard Mid-Cap Growth|0.07;IMCG|iShares Morningstar Mid-Cap Growth|0.06;IWP|iShares Russell Mid-Cap Growth|0.23","Mid growth trades at a premium to its history without the mega-cap balance sheets that justify the large-cap premium. It is the least well-supported rich corner of the domestic grid.","Many constituents are unprofitable or thinly profitable, so the multiple rests on forecasts several years out.","Refinancing at higher rates for companies without cash fortresses;Earnings estimates that historically get cut in the second half;Thinner liquidity in drawdowns than large caps","Nov 2025"],
["usmb","US Mid Blend","US size & style",55,"18.1","24.7","2.8","1.5%","+8%","-6%","-40%","+8%","+8%","+10%","+9.8%","18","0.94","+$4B","VO|Vanguard Mid-Cap|0.04;IJH|iShares Core S&P Mid-Cap|0.05;SPMD|SPDR Portfolio S&P 400|0.03","Sitting almost exactly at its twenty-year median, which is the most honest place on this grid. Mid caps have earnings growth close to large caps at two-thirds the multiple.","The forgotten middle: too small for the index-flow bid, too large to be a small-cap story.","More domestic-revenue exposure, so a US slowdown hits harder;Higher floating-rate debt than large caps;Index turnover pushes winners out into large-cap benchmarks","Nov 2025"],
["usmv","US Mid Value","US size & style",41,"15.3","20.8","2.1","2.3%","+6%","-7%","-39%","+7%","+8%","+10%","+8.7%","17","0.90","+$1B","VOE|Vanguard Mid-Cap Value|0.07;IJJ|iShares S&P Mid-Cap 400 Value|0.18;IWS|iShares Russell Mid-Cap Value|0.23","Below its own median on a blended multiple, with a dividend yield that actually contributes to total return. Industrials and regional financials lead the weighting.","This is where cheapness and quality still overlap in the domestic market.","Regional bank credit quality, particularly commercial real estate;Cyclical earnings — the multiple looks lowest right before earnings fall;Slow re-rating: cheap can stay cheap for years","Nov 2025"],
["ussg","US Small Growth","US size & style",62,"22.9","25.6","4.3","0.4%","+10%","-14%","-46%","+5%","+4%","+8%","+8.9%","23","0.87","-$3B","VBK|Vanguard Small-Cap Growth|0.07;IWO|iShares Russell 2000 Growth|0.24;XSMO|Invesco S&P SmallCap Momentum|0.36","The multiple looks moderate only because loss-making constituents are excluded from the ratio. On a whole-index basis this is the least attractive risk-adjusted corner.","Two-fifths of the underlying names do not earn money, which makes the aggregate P/E a flattering statistic.","A large share of unprofitable constituents;Rate sensitivity through floating-rate borrowing;Biotech binary outcomes drive a meaningful part of the index","Nov 2021"],
["ussb","US Small Blend","US size & style",33,"15.6","19.2","1.9","1.6%","+7%","-11%","-44%","+4%","+5%","+8%","+7.6%","21","0.89","-$1B","IJR|iShares Core S&P Small-Cap|0.06;VB|Vanguard Small-Cap|0.05;SPSM|SPDR Portfolio S&P 600|0.03","Near the cheap end of its own range and roughly a third off large caps on forward earnings. The S&P 600 version screens better than the Russell 2000 because of its profitability requirement.","Small caps have de-rated for four years while earnings held up modestly — the gap is the opportunity.","Refinancing wall over the next 24 months;Domestic-economy sensitivity;Index construction matters more here than in any other slice","Nov 2021"],
["ussv","US Small Value","US size & style",22,"12.4","15.1","1.3","2.4%","+5%","-12%","-45%","+3%","+6%","+9%","+7.1%","22","0.85","+$2B","AVUV|Avantis US Small Cap Value|0.25;VBR|Vanguard Small-Cap Value|0.07;DFSV|Dimensional US Small Cap Value|0.30","The cheapest domestic slice on the board, at the 22nd percentile of its own history and near book value on aggregate. The discount to large-cap growth is close to the widest since 2000.","Historically, entry points in this decile have preceded strong ten-year real returns — with several painful years inside them.","Balance-sheet fragility: leverage sits highest in this cohort;Long dead periods — the 2010s were a decade of underperformance;Screening on price alone catches genuinely impaired businesses","Nov 2021"],
["divg","Dividend Growth","Income & dividend",71,"21.0","29.6","4.0","1.7%","+8%","-3%","-33%","+11%","+10%","+11%","+11.2%","14","0.93","+$14B","VIG|Vanguard Dividend Appreciation|0.05;DGRO|iShares Core Dividend Growth|0.08;NOBL|ProShares S&P 500 Dividend Aristocrats|0.35","Quality compounders have become a crowded defensive trade, and the slice now trades above its own historical norm. The yield is low because the price is high.","You are buying reliability, and reliability is currently expensive.","Priced as a bond proxy in parts — sensitive to real rates;Dividend growth screens concentrate in staples and healthcare;Quality premium can compress without any dividend being cut","Feb 2026"],
["hidiv","High Dividend Yield","Income & dividend",38,"14.2","19.8","2.2","3.6%","+5%","-5%","-36%","+8%","+7%","+9%","+8.4%","13","0.82","+$6B","SCHD|Schwab US Dividend Equity|0.06;VYM|Vanguard High Dividend Yield|0.06;HDV|iShares Core High Dividend|0.08","Modestly below its own median with a yield that covers a real chunk of expected return. Energy, staples and financials carry the weight.","The screen buys yield, so it structurally avoids the expensive end of the market — that is the point, and also the constraint.","Yield screens pick up companies about to cut;Sector concentration in energy and staples;Underperforms badly in narrow growth-led markets","Feb 2026"],
["intdiv","International Dividend","Income & dividend",24,"11.3","13.9","1.4","4.6%","+6%","-6%","-42%","+12%","+9%","+8%","+5.2%","15","0.76","+$3B","VYMI|Vanguard International High Dividend Yield|0.17;IDV|iShares International Select Dividend|0.49;SCHY|Schwab International Dividend Equity|0.14","A 4.6% yield at the 24th percentile of its own valuation history. Non-US companies pay out more of their earnings, so the yield is structural rather than distressed.","Currency is half the story here — dollar weakness would add to the return, dollar strength would take from it.","Withholding tax drags on the headline yield in taxable accounts;Currency swings can exceed the yield in a single year;Heavier weighting to European banks and telecoms","Jul 2007"],
["covcall","Covered-Call Income","Income & dividend",57,"19.0","32.5","4.6","7.9%","+9%","-4%","-30%","+9%","+8%","+9%","+8.0%","11","0.85","+$18B","JEPI|JPMorgan Equity Premium Income|0.35;JEPQ|JPMorgan Nasdaq Equity Premium|0.35;DIVO|Amplify CWP Enhanced Dividend|0.56","The distribution is option premium, not earnings — it looks like yield and behaves like sold upside. Underlying equity is priced near the rich end of its history.","Volatility is low, so the premium being harvested is low too. This is the worst environment in which to sell it.","Distribution is not income in the tax sense and can fall sharply;Caps upside in exactly the markets equities need to work;Fees are five to ten times a plain index fund","Feb 2026"],
["intdev","Developed Markets","International",49,"14.6","19.1","1.9","2.9%","+8%","-4%","-38%","+13%","+11%","+9%","+6.1%","15","0.86","+$22B","VEA|Vanguard FTSE Developed Markets|0.05;IEFA|iShares Core MSCI EAFE|0.07;SPDW|SPDR Portfolio Developed World ex-US|0.03","Right at its own median, and roughly a 35% multiple discount to the US. Part of that discount is composition — fewer software companies, more banks and industrials.","The relevant question is not whether it is cheaper than the US, but whether it is cheap against itself. It is not — it is ordinary.","Currency exposure is unhedged in these funds;Europe and Japan carry demographic and energy-cost headwinds;The discount to the US has persisted for fifteen years","Feb 2026"],
["intdv","Developed Value","International",27,"11.8","14.6","1.3","4.1%","+7%","-5%","-41%","+15%","+12%","+9%","+5.0%","16","0.82","+$4B","EFV|iShares MSCI EAFE Value|0.34;AVIV|Avantis International Large Cap Value|0.25;IVLU|iShares MSCI Intl Value Factor|0.30","Under twelve times forward earnings at the 27th percentile of its own range, with a yield above four percent. Cheapness on this axis has historically mattered most over five to ten years.","Japanese and European corporate governance reform is a genuine, slow-moving catalyst rather than a story.","Bank-heavy exposure ties returns to European credit;Governance reform can stall for years;Value indices abroad hold more state-influenced companies","Oct 2007"],
["intsm","Developed Small","International",24,"13.1","15.8","1.2","3.3%","+6%","-12%","-46%","+10%","+7%","+6%","+5.4%","17","0.83","+$1B","AVDV|Avantis International Small Cap Value|0.36;SCZ|iShares MSCI EAFE Small-Cap|0.40;VSS|Vanguard FTSE All-World ex-US Small-Cap|0.08","The most neglected equity slice on the board: small, foreign, and unowned. Trading near book value with a 3.3% yield.","Nobody markets this exposure, which is usually a precondition for it being cheap.","Wide bid-offer spreads and lower liquidity;Domestic-economy exposure in slow-growth countries;Currency adds volatility on top of small-cap volatility","Jun 2021"],
["japan","Japan","International",58,"16.4","23.7","1.7","2.2%","+9%","-6%","-37%","+14%","+13%","+11%","+7.2%","16","0.70","+$9B","BBJP|JPMorgan BetaBuilders Japan|0.19;EWJ|iShares MSCI Japan|0.50;DXJ|WisdomTree Japan Hedged Equity|0.48","Above its own median after a three-year re-rating driven by buybacks and cross-shareholding unwinds. Still under two times book, which flatters it relative to the multiple.","The reform story is real and is now partly in the price. Hedged and unhedged versions have diverged sharply — pick deliberately.","Yen direction dominates dollar returns;Reform momentum depends on continued exchange pressure;Domestic demographics cap long-run growth","Aug 2026"],
["europe","Europe","International",44,"14.2","19.6","2.0","3.1%","+7%","-4%","-39%","+14%","+11%","+9%","+5.9%","16","0.85","+$7B","VGK|Vanguard FTSE Europe|0.09;IEUR|iShares Core MSCI Europe|0.09;FEZ|SPDR Euro Stoxx 50|0.29","Slightly below its own median with a 3.1% yield. The index is more global than the continent — a large share of revenue is earned outside Europe.","Cheap enough to be interesting, not cheap enough to be a table-pounder.","Energy input costs remain structurally higher than pre-2022;Bank exposure to sovereign and property credit;Political fragmentation slows fiscal response","Feb 2026"],
["em","Emerging Markets","International",31,"12.7","14.2","1.7","2.7%","+11%","-9%","-49%","+17%","+9%","+7%","+4.3%","18","0.78","+$12B","IEMG|iShares Core MSCI Emerging Markets|0.09;VWO|Vanguard FTSE Emerging Markets|0.07;SPEM|SPDR Portfolio Emerging Markets|0.07","Just inside the cheap third of its own history, with faster earnings growth than developed markets. Taiwan and Korea semiconductors now drive much of the index.","What you are actually buying has changed: this is closer to a technology hardware index with an Asian domicile than a commodity-exporter basket.","Semiconductor cycle now dominates index earnings;China weight brings policy and geopolitical risk;Dollar strength has historically been the single biggest headwind","Oct 2007"],
["emv","EM Value","International",15,"9.4","10.3","1.0","4.4%","+9%","-14%","-52%","+16%","+8%","+7%","+3.6%","19","0.74","+$2B","AVES|Avantis Emerging Markets Value|0.36;FNDE|Schwab Fundamental Emerging Markets|0.39;DGS|WisdomTree EM SmallCap Dividend|0.58","The cheapest slice on the entire board — under ten times forward earnings, at book value, at the 15th percentile of its own range. A 4.4% yield is being paid to wait.","Extreme cheapness of this kind is usually compensation for governance, currency and political risk rather than a free lunch. Position sizing is the entire discussion.","State-owned enterprises with shareholders second in line;Currency devaluation can erase local equity gains in dollars;Capital-controls and delisting risk in the tail","Oct 2007"],
["emxc","EM ex-China","International",47,"15.1","17.9","2.1","2.3%","+12%","-7%","-44%","+15%","+12%","+10%","+6.0%","18","0.76","+$5B","EMXC|iShares MSCI EM ex-China|0.25;XCEM|Columbia EM Core ex-China|0.16;EMXF|iShares ESG Advanced EM ex-China|0.16","Removing China removes the discount: this version trades near its own median because India and Taiwan carry premium multiples. You are paying to avoid a risk, and the price is explicit.","Useful as a governance decision, not a valuation one.","India's multiple is high on any historical measure;Taiwan concentration is a single-industry, single-strait risk;Higher fees than plain EM for the same underlying markets","Feb 2026"],
["china","China","International",8,"10.1","11.4","1.2","2.9%","+10%","-38%","-60%","+22%","+4%","+2%","+1.9%","26","0.50","-$6B","MCHI|iShares MSCI China|0.59;FXI|iShares China Large-Cap|0.74;KWEB|KraneShares CSI China Internet|0.70","At the 8th percentile of its own twenty-year range and 38% below its all-time high — statistically the deepest discount available. Earnings at the large internet platforms have recovered while the multiple has not.","This is the clearest example on the board of cheap-for-a-reason: the discount is a policy and property-cycle discount, and it can persist or widen regardless of earnings.","Policy intervention can reprice an entire sector overnight;Property-sector deleveraging still working through household balance sheets;Delisting and index-exclusion risk for US-listed holders;Demographics and deflation pressure nominal growth","Feb 2021"],
["gold","Gold","Real assets",88,"—","—","—","0.0%","—","-1%","-45%","+26%","+19%","+14%","+9.4%","15","0.10","+$31B","GLDM|SPDR Gold MiniShares|0.10;IAU|iShares Gold Trust|0.25;GLD|SPDR Gold Shares|0.40","Real price sits at the 88th percentile of its twenty-year range after central-bank buying and a debasement bid. There are no earnings to grow into the price.","Gold has done its job; the entry point is now the worst it has been outside 2011 and 1980 in real terms.","No cash flow — the entire return is the change in what someone else will pay;Real-rate increases have historically been the main drag;Central-bank demand is policy-driven and can stop abruptly","Aug 2026"],
["silver","Silver","Real assets",76,"—","—","—","0.0%","—","-6%","-70%","+34%","+22%","+16%","+8.1%","27","0.25","+$6B","SLV|iShares Silver Trust|0.50;SIVR|abrdn Physical Silver|0.30;SIL|Global X Silver Miners|0.65","Half monetary metal, half industrial input, and priced at the high end of its own range but below its 1980 and 2011 peaks. Solar demand has changed the underlying balance.","Expect roughly twice gold's volatility in both directions — that has been true in every cycle.","Industrial demand ties it to the manufacturing cycle;Far more volatile than gold with the same lack of cash flow;Above-ground inventories are opaque","Apr 2011"],
["bcom","Broad Commodities","Real assets",29,"—","—","—","0.0%","—","-19%","-62%","+4%","+2%","+7%","+1.4%","15","0.35","+$2B","PDBC|Invesco Optimum Yield Diversified Commodity|0.59;COMT|iShares GSCI Commodity Dynamic Roll|0.48;DBC|Invesco DB Commodity Index|0.87","Below its own median and 19% under its all-time high, with the roll yield currently positive in energy. The diversification case is stronger than the return case.","This slice earns its place through low correlation to equities, not through expected return.","Roll cost can quietly consume returns in contango markets;Long dead decades — the 2010s were deeply negative;K-1 versus 1099 tax treatment differs by fund structure","Jun 2008"],
["energy","Energy Equity","Real assets",26,"12.6","14.4","1.9","3.4%","+2%","-9%","-58%","+6%","+12%","+21%","+6.8%","22","0.60","-$4B","XLE|Energy Select Sector SPDR|0.09;VDE|Vanguard Energy|0.09;XOP|SPDR Oil & Gas Exploration|0.35","Under thirteen times forward earnings at the 26th percentile of its own range, with capital discipline holding and buybacks running. The market is pricing a structural decline in demand.","Free cash flow yields here are the highest of any equity slice on the board, which is either an opportunity or a warning about terminal value.","Terminal-value risk if electrification accelerates;Oil price is the earnings driver and is not forecastable;Capital discipline has historically broken at the top of the cycle","Jun 2014"],
["gminers","Gold Miners","Real assets",69,"14.8","16.2","2.4","1.4%","+28%","-8%","-66%","+55%","+31%","+19%","+6.2%","33","0.35","+$4B","GDX|VanEck Gold Miners|0.51;RING|iShares MSCI Global Gold Miners|0.39;GDXJ|VanEck Junior Gold Miners|0.52","Miners have finally converted a high gold price into margin, and the multiple has re-rated with it. Above its own median but well below the metal on a percentile basis.","This is leveraged exposure to the gold price minus operational risk — historically a poor long-term hold and a strong cyclical one.","Cost inflation eats the margin the metal creates;Jurisdiction and expropriation risk in several major producers;Equity dilution has destroyed per-share value across cycles","Apr 2011"],
["copper","Copper & Industrial Metals","Real assets",44,"16.1","18.4","2.0","2.1%","+9%","-11%","-64%","+18%","+9%","+13%","+5.5%","28","0.55","+$3B","COPX|Global X Copper Miners|0.65;PICK|iShares MSCI Global Metals & Mining|0.39;CPER|United States Copper Index|0.97","Near its own median, with a supply picture — few new large deposits, long permitting timelines — that is more compelling than the current multiple.","The electrification demand story is real but slower than headlines imply; the supply constraint is the more reliable half of the thesis.","Chinese construction demand still sets the marginal price;Mine-development timelines mean supply responses arrive years late;Deeply cyclical earnings make the P/E misleading at turns","Mar 2022"]
];

const FIELDS = ["key","name","group","pct","fwdPE","cape","pb","yld","eps","ath","dd","r1","r3","r5","r10","vol","corr","flow","etfs","take","take2","risks","athDate"];
const SLICES = D.map(a => {
  const o = {}; FIELDS.forEach((f, i) => o[f] = a[i]);
  o.etfList = o.etfs.split(";").map(s => { const p = s.split("|"); return { ticker: p[0], name: p[1], er: p[2] }; });
  o.riskList = o.risks.split(";").map((t, i) => ({ n: String(i + 1).padStart(2, "0"), text: t }));
  return o;
});
const BY = {}; SLICES.forEach(s => BY[s.key] = s);

function verdict(p) { return p < 30 ? "CHEAP" : p > 70 ? "RICH" : "FAIR"; }
function ink(p) { return p < 30 ? "#2c455d" : p < 50 ? "#416180" : p < 70 ? "#749dc4" : p < 85 ? "#b7b7ba" : "#d4d4d7"; }
function textInk(p) { return p < 30 ? "#2c455d" : p < 50 ? "#416180" : p < 70 ? "#597ea3" : "#7a7a7d"; }
function pctLine(p) { return p >= 50 ? `Only ${100 - p}% of the last 20 years was more expensive than today.` : `Cheaper than today in only ${p}% of the last 20 years.`; }
function tagStyle(p) {
  const v = verdict(p);
  const base = { font: "600 9.5px var(--font-body)", letterSpacing: ".1em", padding: "3px 6px", flex: "none", whiteSpace: "nowrap" };
  if (v === "CHEAP") return Object.assign({}, base, { background: "var(--color-accent)", color: "#fff" });
  if (v === "FAIR") return Object.assign({}, base, { background: "var(--color-accent-200)", color: "var(--color-accent-800)" });
  return Object.assign({}, base, { border: "1px solid var(--color-neutral-700)", color: "var(--color-neutral-800)", padding: "2px 5px" });
}
function rng(seed) { let s = seed % 2147483647; if (s <= 0) s += 2147483646; return () => (s = s * 16807 % 2147483647) / 2147483647; }
function hash(k) { let h = 7; for (let i = 0; i < k.length; i++) h = (h * 31 + k.charCodeAt(i)) % 100000; return h; }
function series(key, pct, n) {
  const r = rng(hash(key) + 13), out = []; let v = 50 + (r() - 0.5) * 40;
  for (let i = 0; i < n; i++) { v += (r() - 0.5) * 22 + (50 - v) * 0.06; out.push(v); }
  const shift = pct - out[n - 1];
  return out.map((x, i) => Math.max(3, Math.min(97, x + shift * (i / (n - 1)) ** 0.6)));
}
function poly(vals, w, h) {
  const n = vals.length;
  return vals.map((v, i) => `${(i / (n - 1) * w).toFixed(1)},${(h - v / 100 * h).toFixed(1)}`).join(" ");
}


module.exports = { SLICES, BY };
